title: [Angad Sahni](https://angadsahni93.github.io/)
description: Slate is a theme for GitHub Pages.
show_downloads: false
google_analytics: Neuroscience, Anhedonia, Reinforcement, learning, machine, reward, effort, esm, experience sampling methodology.
theme: jekyll-theme-slate
