title: Angad Sahni
description: Record of PhD & personal academic work
show_downloads: false
google_analytics: Neuroscience, Anhedonia, Reinforcement, learning, machine, reward, effort, esm, experience sampling methodology.
theme: jekyll-theme-slate
