title: Angad Sahni
description: PhD Candidate in Neuroscience
show_downloads: false
google_analytics: Neuroscience, Anhedonia, Reinforcement, learning, machine, reward, effort, esm, experience sampling methodology.
theme: jekyll-theme-slate
